__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
 recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call la__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
st):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", li__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
ne 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__

    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return sel__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
f.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\codi__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
ng\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widge__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
ts.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 83__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
3, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
   __nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
 return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELEC__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
T %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WH__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
__nonzero__
ERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (c__nonzero__
__nonzero__
__nonzero__
ol, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\coding\niblet\widgets.py", line 859, in data
    return self.value(index)
  File "D:\coding\niblet\widgets.py", line 833, in value
    return self.db.get_one("SELECT %s FROM %s WHERE id=%s" % (col, self.table, ID))
  File "D:\coding\niblet\db.py", line 64, in get_one
    if row:
TypeError: 'NoneType' object is not callable
